[build]
builder = "railpack"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
preDeployCommand = ["python manage.py migrate --noinput"]
startCommand = "gunicorn -c gunicorn.conf.py config.wsgi:application"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
